[project]
name = "classificationmodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "tensorboard>=2.20.0",
    "torch",
    "torchvision>=0.23.0",
    "tqdm>=4.67.1",
]
